apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hrel-scanner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hrel-scanner
    spec:
      containers:
        - name: hrel-scanner
          image: eu.gcr.io/hrel-168422/hrel:master
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - while true; do hrel-scanner; sleep 1200; done
          env:
            - name: PGINFO
              value: "host=hrel-database user=hrel dbname=hrel"